// <auto-generated />
using System;
using ArgusMedia.Restaurant.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArgusMedia.Restaurant.Migrations
{
    [DbContext(typeof(RestaurantDbContex))]
    partial class RestaurantDbContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArgusMedia.Restaurant.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ArgusMedia.Restaurant.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDrink")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25254a12-e89e-4eb5-8e21-a5fc38625d01"),
                            IsDrink = false,
                            Name = "Mains",
                            Price = 7m
                        },
                        new
                        {
                            Id = new Guid("25254a12-e89e-4eb5-8e21-a5fc38625d02"),
                            IsDrink = false,
                            Name = "Mains",
                            Price = 4m
                        },
                        new
                        {
                            Id = new Guid("25254a12-e89e-4eb5-8e21-a5fc38625d03"),
                            IsDrink = true,
                            Name = "Mains",
                            Price = 2.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
